=== EcoEnvAI/DEXiWare/node_api/business_logic/lib/true_evaluator/_validation/evaluation.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "true_evaluator_evaluation_schema",
  "type": "object",
  "title": "Evaluation-based schema",
  "description": "Evaluation-based schema validates operation with similar structure",
  "default": {},
  "required": [
    "operation",
    "output",
    "model",
    "model_path",
    "alternatives"
  ],
  "additionalProperties": false,
  "properties": {
    "operation": {
      "$id": "#/properties/operation",
      "type": "string",
      "enum": ["evaluation","partial_evaluation"],
      "title": "Operation",
      "description": "Operation to be executed",
      "default": "evaluation"
    },
    "output": {
      "$id": "#/properties/output",
      "type": "string",
      "enum": [ "flat", "tree" ],
      "title": "Output",
      "description": "Structure the output need to be formatted like",
      "default": "flat"
    },
    "model": {
      "$id": "#/properties/model",
      "type": "string",
      "title": "Model name",
      "description": "Model to be used in evaluation"
    },
    "model_path": {
      "$id": "#/properties/model_path",
      "type": "string",
      "title": "DEX model path",
      "description": "Absolute path to the DEX model"
    },
    "undefined_value": {
      "$id": "#/properties/undefined_value",
      "type": "string",
      "title": "DEX treat of null values",
      "description": "DEX treat of null values"
    },
    "alternatives": {
      "$id": "#/properties/alternatives",
      "type": "array",
      "title": "Alternatives",
      "description": "Array of alternatives to be evaluated",
      "default": [],
      "additionalItems": false,
      "items": {
        "anyOf": [
          {
            "$id": "#/properties/alternatives/items/anyOf/0",
            "type": "object",
            "title": "Single alternative",
            "description": "Description of an alternative",
            "default": {},
            "required": [
              "alternative",
              "inputs"
            ],
            "additionalProperties": false,
            "properties": {
              "alternative": {
                "$id": "#/properties/alternatives/items/anyOf/0/properties/alternative",
                "type": "string",
                "title": "Alternative name",
                "description": "Descriptive name for a given alternative"
              },
              "inputs": {
                "$id": "#/properties/alternatives/items/anyOf/0/properties/inputs",
                "type": "array",
                "title": "Input attributes",
                "description": "Array of input attributes",
                "default": [],
                "additionalItems": false,
                "items": {
                  "anyOf": [
                    {
                      "$id": "#/properties/alternatives/items/anyOf/0/properties/inputs/items/anyOf/0",
                      "type": "object",
                      "title": "Input attribute",
                      "description": "Input attribute",
                      "default": {},
                      "required": [
                        "values"
                      ],
                      "additionalProperties": false,
                      "properties": {
                        "values": {
                          "$id": "#/properties/alternatives/items/anyOf/0/properties/inputs/items/anyOf/0/properties/values",
                          "type": "array",
                          "title": "Value",
                          "description": "Value of input attribute",
                          "additionalItems": false,
                          "items": {
                            "anyOf": [
                              {
                                "$id": "#/properties/alternatives/items/anyOf/0/properties/inputs/items/anyOf/0/properties/values/items/anyOf/0",
                                "type": "string",
                                "title": "Single value",
                                "description": "Single value of input attribute"
                              },
                              {
                                "$id": "#/properties/alternatives/items/anyOf/0/properties/inputs/items/anyOf/0/properties/values/items/anyOf/1",
                                "type": "number",
                                "title": "Single value",
                                "description": "Single value of input attribute"
                              }
                            ],
                            "$id": "#/properties/alternatives/items/anyOf/0/properties/inputs/items/anyOf/0/properties/values/items"
                          }
                        },
                        "attribute": {
                          "$id": "#/properties/alternatives/items/anyOf/0/properties/inputs/items/anyOf/0/properties/attribute",
                          "type": "string",
                          "title": "Attribute name",
                          "description": "Name of input attribute"
                        },
                        "path": {
                          "$id": "#/properties/alternatives/items/anyOf/0/properties/inputs/items/anyOf/0/properties/path",
                          "type": "string",
                          "title": "Attribute path",
                          "description": "Path of input attribute"
                        }
                      },
                      "oneOf": [
                        {
                          "required": [ "attribute" ]
                        },
                        {
                          "required": [ "path" ]
                        }
                      ]
                    }
                  ],
                  "$id": "#/properties/alternatives/items/anyOf/0/properties/inputs/items"
                }
              }
            }
          }
        ],
        "$id": "#/properties/alternatives/items"
      }
    }
  }
}

=== EcoEnvAI/DEXiWare/node_api/business_logic/lib/true_evaluator/inp/ChainPartialFlat.json
{
    "operation": "partial_evaluation",
    "output": "flat",
    "model": "AgriFoodChainIntegrated",
    "model_path": "models/AgriFoodChainIntegrated.dxi",
    "alternatives": [{
            "alternative": "ChainLowEnvironmental",
            "inputs": [{
                    "values": ["Low"],
                    "attribute": "EnvironmentalPillar"
                }, {
                    "values": ["Low"],
                    "attribute": "Production_EconomicPillar"
                }, {
                    "values": ["Low"],
                    "attribute": "Processing_EconomicPillar"
                }, {
                    "values": ["Low"],
                    "attribute": "Tranportation_EconomicPillar"
                }, {
                    "values": ["Low"],
                    "attribute": "Market_EconomicPillar"
                }, {
                    "values": ["Low"],
                    "attribute": "Consumers_EconomicPillar"
                }, {
                    "values": ["Low"],
                    "attribute": "Production_SocialPolicyPillar"
                }, {
                    "values": ["Low"],
                    "attribute": "Processing_SocialPolicyPillar"
                }, {
                    "values": ["Low"],
                    "attribute": "Tranportation_SocialPolicyPillar"
                }, {
                    "values": ["Low"],
                    "attribute": "Market_SocialPolicyPillar"
                }, {
                    "values": ["Low"],
                    "attribute": "Consumers_SocialPolicyPillar"
                }
            ]
        }, {
            "alternative": "ChainMediumEconomic",
            "inputs": [{
                    "values": ["Medium"],
                    "attribute": "Production_EnvironmentalPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Processing_EnvironmentalPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Tranportation_EnvironmentalPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Market_EnvironmentalPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Consumers_EnvironmentalPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "EconomicPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Production_SocialPolicyPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Processing_SocialPolicyPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Tranportation_SocialPolicyPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Market_SocialPolicyPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Consumers_SocialPolicyPillar"
                }
            ]
        }, {
            "alternative": "ChainHighSocial",
            "inputs": [{
                    "values": ["High"],
                    "attribute": "Production_EnvironmentalPillar"
                }, {
                    "values": ["High"],
                    "attribute": "Processing_EnvironmentalPillar"
                }, {
                    "values": ["High"],
                    "attribute": "Tranportation_EnvironmentalPillar"
                }, {
                    "values": ["High"],
                    "attribute": "Market_EnvironmentalPillar"
                }, {
                    "values": ["High"],
                    "attribute": "Consumers_EnvironmentalPillar"
                }, {
                    "values": ["High"],
                    "attribute": "Production_EconomicPillar"
                }, {
                    "values": ["High"],
                    "attribute": "Processing_EconomicPillar"
                }, {
                    "values": ["High"],
                    "attribute": "Tranportation_EconomicPillar"
                }, {
                    "values": ["High"],
                    "attribute": "Market_EconomicPillar"
                }, {
                    "values": ["High"],
                    "attribute": "Consumers_EconomicPillar"
                }, {
                    "values": ["High"],
                    "attribute": "Social-PolicyPillar"
                }
            ]
        }, {
            "alternative": "ChainMedium*Transport",
            "inputs": [{
                    "values": ["Medium"],
                    "attribute": "Production_EnvironmentalPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Processing_EnvironmentalPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Market_EnvironmentalPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Consumers_EnvironmentalPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Production_EconomicPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Processing_EconomicPillar"
                }, {
                    "values": ["Low", "Medium", "High"],
                    "attribute": "Tranportation_EconomicPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Market_EconomicPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Consumers_EconomicPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Production_SocialPolicyPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Processing_SocialPolicyPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Market_SocialPolicyPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Consumers_SocialPolicyPillar"
                }
            ]
        }
    ]
}

=== EcoEnvAI/DEXiWare/node_api/business_logic/lib/true_evaluator/inp/ChainFlatPositional.json
{
    "operation": "evaluation",
    "output": "flat",
    "model": "AgriFoodChainIntegrated",
    "model_path": "models/AgriFoodChainIntegrated.dxi",
    "alternatives": [{
            "alternative": "ChainLow",
            "inputs": [{
                    "values": [0],
                    "attribute": "Production_EnvironmentalPillar"
                }, {
                    "values": [0],
                    "attribute": "Processing_EnvironmentalPillar"
                }, {
                    "values": [0],
                    "attribute": "Tranportation_EnvironmentalPillar"
                }, {
                    "values": [0],
                    "attribute": "Market_EnvironmentalPillar"
                }, {
                    "values": [0],
                    "attribute": "Consumers_EnvironmentalPillar"
                }, {
                    "values": [0],
                    "attribute": "Production_EconomicPillar"
                }, {
                    "values": [0],
                    "attribute": "Processing_EconomicPillar"
                }, {
                    "values": [0],
                    "attribute": "Tranportation_EconomicPillar"
                }, {
                    "values": [0],
                    "attribute": "Market_EconomicPillar"
                }, {
                    "values": [0],
                    "attribute": "Consumers_EconomicPillar"
                }, {
                    "values": [0],
                    "attribute": "Production_SocialPolicyPillar"
                }, {
                    "values": [0],
                    "attribute": "Processing_SocialPolicyPillar"
                }, {
                    "values": [0],
                    "attribute": "Tranportation_SocialPolicyPillar"
                }, {
                    "values": [0],
                    "attribute": "Market_SocialPolicyPillar"
                }, {
                    "values": [0],
                    "attribute": "Consumers_SocialPolicyPillar"
                }
            ]
        }, {
            "alternative": "ChainMedium",
            "inputs": [{
                    "values": [1],
                    "attribute": "Production_EnvironmentalPillar"
                }, {
                    "values": [1],
                    "attribute": "Processing_EnvironmentalPillar"
                }, {
                    "values": [1],
                    "attribute": "Tranportation_EnvironmentalPillar"
                }, {
                    "values": [1],
                    "attribute": "Market_EnvironmentalPillar"
                }, {
                    "values": [1],
                    "attribute": "Consumers_EnvironmentalPillar"
                }, {
                    "values": [1],
                    "attribute": "Production_EconomicPillar"
                }, {
                    "values": [1],
                    "attribute": "Processing_EconomicPillar"
                }, {
                    "values": [1],
                    "attribute": "Tranportation_EconomicPillar"
                }, {
                    "values": [1],
                    "attribute": "Market_EconomicPillar"
                }, {
                    "values": [1],
                    "attribute": "Consumers_EconomicPillar"
                }, {
                    "values": [1],
                    "attribute": "Production_SocialPolicyPillar"
                }, {
                    "values": [1],
                    "attribute": "Processing_SocialPolicyPillar"
                }, {
                    "values": [1],
                    "attribute": "Tranportation_SocialPolicyPillar"
                }, {
                    "values": [1],
                    "attribute": "Market_SocialPolicyPillar"
                }, {
                    "values": [1],
                    "attribute": "Consumers_SocialPolicyPillar"
                }
            ]
        }, {
            "alternative": "ChainHigh",
            "inputs": [{
                    "values": [2],
                    "attribute": "Production_EnvironmentalPillar"
                }, {
                    "values": [2],
                    "attribute": "Processing_EnvironmentalPillar"
                }, {
                    "values": [2],
                    "attribute": "Tranportation_EnvironmentalPillar"
                }, {
                    "values": [2],
                    "attribute": "Market_EnvironmentalPillar"
                }, {
                    "values": [2],
                    "attribute": "Consumers_EnvironmentalPillar"
                }, {
                    "values": [2],
                    "attribute": "Production_EconomicPillar"
                }, {
                    "values": [2],
                    "attribute": "Processing_EconomicPillar"
                }, {
                    "values": [2],
                    "attribute": "Tranportation_EconomicPillar"
                }, {
                    "values": [2],
                    "attribute": "Market_EconomicPillar"
                }, {
                    "values": [2],
                    "attribute": "Consumers_EconomicPillar"
                }, {
                    "values": [2],
                    "attribute": "Production_SocialPolicyPillar"
                }, {
                    "values": [2],
                    "attribute": "Processing_SocialPolicyPillar"
                }, {
                    "values": [2],
                    "attribute": "Tranportation_SocialPolicyPillar"
                }, {
                    "values": [2],
                    "attribute": "Market_SocialPolicyPillar"
                }, {
                    "values": [2],
                    "attribute": "Consumers_SocialPolicyPillar"
                }
            ]
        }, {
            "alternative": "ChainMedium*Transport",
            "inputs": [{
                    "values": [1],
                    "attribute": "Production_EnvironmentalPillar"
                }, {
                    "values": [1],
                    "attribute": "Processing_EnvironmentalPillar"
                }, {
                    "values": [1],
                    "attribute": "Market_EnvironmentalPillar"
                }, {
                    "values": [1],
                    "attribute": "Consumers_EnvironmentalPillar"
                }, {
                    "values": [1],
                    "attribute": "Production_EconomicPillar"
                }, {
                    "values": [1],
                    "attribute": "Processing_EconomicPillar"
                }, {
                    "values": [0, 1, 2],
                    "attribute": "Tranportation_EconomicPillar"
                }, {
                    "values": [1],
                    "attribute": "Market_EconomicPillar"
                }, {
                    "values": [1],
                    "attribute": "Consumers_EconomicPillar"
                }, {
                    "values": [1],
                    "attribute": "Production_SocialPolicyPillar"
                }, {
                    "values": [1],
                    "attribute": "Processing_SocialPolicyPillar"
                }, {
                    "values": [1],
                    "attribute": "Market_SocialPolicyPillar"
                }, {
                    "values": [1],
                    "attribute": "Consumers_SocialPolicyPillar"
                }
            ]
        }
    ]
}

=== EcoEnvAI/DEXiWare/node_api/business_logic/lib/true_evaluator/inp/ChainSubtree.json
{
    "operation": "evaluation",
    "output": "tree",
    "model": "AgriFoodChainIntegrated",
    "model_path": "models/AgriFoodChainIntegrated.dxi",
    "alternatives": [{
            "alternative": "ChainLow",
            "inputs": [{
                    "values": ["Low"],
                    "attribute": "Production_EnvironmentalPillar"
                }, {
                    "values": ["Low"],
                    "attribute": "Processing_EnvironmentalPillar"
                }, {
                    "values": ["Low"],
                    "attribute": "Tranportation_EnvironmentalPillar"
                }, {
                    "values": ["Low"],
                    "attribute": "Market_EnvironmentalPillar"
                }, {
                    "values": ["Low"],
                    "attribute": "Consumers_EnvironmentalPillar"
                }, {
                    "values": ["Low"],
                    "attribute": "Production_EconomicPillar"
                }, {
                    "values": ["Low"],
                    "attribute": "Processing_EconomicPillar"
                }, {
                    "values": ["Low"],
                    "attribute": "Tranportation_EconomicPillar"
                }, {
                    "values": ["Low"],
                    "attribute": "Market_EconomicPillar"
                }, {
                    "values": ["Low"],
                    "attribute": "Consumers_EconomicPillar"
                }, {
                    "values": ["Low"],
                    "attribute": "Production_SocialPolicyPillar"
                }, {
                    "values": ["Low"],
                    "attribute": "Processing_SocialPolicyPillar"
                }, {
                    "values": ["Low"],
                    "attribute": "Tranportation_SocialPolicyPillar"
                }, {
                    "values": ["Low"],
                    "attribute": "Market_SocialPolicyPillar"
                }, {
                    "values": ["Low"],
                    "attribute": "Consumers_SocialPolicyPillar"
                }
            ]
        }, {
            "alternative": "ChainMedium",
            "inputs": [{
                    "values": ["Medium"],
                    "attribute": "Production_EnvironmentalPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Processing_EnvironmentalPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Tranportation_EnvironmentalPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Market_EnvironmentalPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Consumers_EnvironmentalPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Production_EconomicPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Processing_EconomicPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Tranportation_EconomicPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Market_EconomicPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Consumers_EconomicPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Production_SocialPolicyPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Processing_SocialPolicyPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Tranportation_SocialPolicyPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Market_SocialPolicyPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Consumers_SocialPolicyPillar"
                }
            ]
        }, {
            "alternative": "ChainHigh",
            "inputs": [{
                    "values": ["High"],
                    "attribute": "Production_EnvironmentalPillar"
                }, {
                    "values": ["High"],
                    "attribute": "Processing_EnvironmentalPillar"
                }, {
                    "values": ["High"],
                    "attribute": "Tranportation_EnvironmentalPillar"
                }, {
                    "values": ["High"],
                    "attribute": "Market_EnvironmentalPillar"
                }, {
                    "values": ["High"],
                    "attribute": "Consumers_EnvironmentalPillar"
                }, {
                    "values": ["High"],
                    "attribute": "Production_EconomicPillar"
                }, {
                    "values": ["High"],
                    "attribute": "Processing_EconomicPillar"
                }, {
                    "values": ["High"],
                    "attribute": "Tranportation_EconomicPillar"
                }, {
                    "values": ["High"],
                    "attribute": "Market_EconomicPillar"
                }, {
                    "values": ["High"],
                    "attribute": "Consumers_EconomicPillar"
                }, {
                    "values": ["High"],
                    "attribute": "Production_SocialPolicyPillar"
                }, {
                    "values": ["High"],
                    "attribute": "Processing_SocialPolicyPillar"
                }, {
                    "values": ["High"],
                    "attribute": "Tranportation_SocialPolicyPillar"
                }, {
                    "values": ["High"],
                    "attribute": "Market_SocialPolicyPillar"
                }, {
                    "values": ["High"],
                    "attribute": "Consumers_SocialPolicyPillar"
                }
            ]
        }, {
            "alternative": "ChainMedium*Transport",
            "inputs": [{
                    "values": ["Medium"],
                    "attribute": "Production_EnvironmentalPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Processing_EnvironmentalPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Market_EnvironmentalPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Consumers_EnvironmentalPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Production_EconomicPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Processing_EconomicPillar"
                }, {
                    "values": ["Low", "Medium", "High"],
                    "attribute": "Tranportation_EconomicPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Market_EconomicPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Consumers_EconomicPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Production_SocialPolicyPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Processing_SocialPolicyPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Market_SocialPolicyPillar"
                }, {
                    "values": ["Medium"],
                    "attribute": "Consumers_SocialPolicyPillar"
                }
            ]
        }
    ]
}
